export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const RETRIEVE_USER = "RETRIEVE_USER";
export const DELETE_USER = "DELETE_USER";

export const RETRIEVE_HOUSEHOLDS_SUCCESS = "RETRIEVE_HOUSEHOLDS_SUCCESS";
export const RETRIEVE_HOUSEHOLDS_FAIL = "RETRIEVE_HOUSEHOLDS_FAIL";
export const RETRIEVE_HOUSEHOLDS_BEGIN = "RETRIEVE_HOUSEHOLDS_BEGIN";

export const RETRIEVE_TRANSACTIONS = "RETRIEVE_TRANSACTIONS";

export const RETRIEVE_PRODUCTS = "RETRIEVE_PRODUCTS";

